version: 2

jobs:
  build:
    working_directory: ~/realworld
    docker:
      - image: circleci/node:lts
    steps:

      - checkout

      - restore_cache:
          key: v0.1-yarn-cache-{{ .Branch }}-{{ checksum "package.json" }}

      - restore_cache:
          key: v0.1-spago-cache-{{ .Branch }}-{{ checksum "packages.dhall" }}

      - run:
          name: Install PureScript and NPM dependencies
          command: yarn

      - run:
          name: Verify the project builds successfully
          command: yarn run build

      - save_cache:
          key: v0.1-yarn-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/realworld/node_modules

      - save_cache:
          key: v0.1-spago-cache-{{ .Branch }}-{{ checksum "packages.dhall" }}
          paths:
            - ~/realworld/.spago
